package ru.sfedu.aems.enums;

public enum TypeOfWork {
    VERIFICATION_SI,
    CALIBRATION_SI,
    TESTING_OF_SI_AND_REFERENCE_MATERIALS,
    MEASUREMENT_METHOD_CERTIFICATION,
    ACCREDITATION_OF_LEGAL_ENTITIES_AND_INDIVIDUAL_ENTREPRENEURS
}